# Generated by Django 5.2.12 on 2026-10-01 17:52

import django.core.validators
import django.db.models.deletion
import fleet.models
import fleet.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('certification_number', fleet.models.UpperCaseCharField(error_messages={'unique': 'A mechanic with this certification number already exists.'}, max_length=30, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', fleet.models.UpperCaseCharField(error_messages={'unique': 'A vehicle with this VIN already exists.'}, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 17-character VIN (letters I, O and Q are not used).', regex='^[A-HJ-NPR-Z0-9]{17}$')], verbose_name='VIN')),
                ('license_plate', fleet.models.UpperCaseCharField(max_length=10, validators=[django.core.validators.RegexValidator(message='License plates may only contain letters, digits, spaces and hyphens.', regex='^[A-Z0-9][A-Z0-9 -]*$')])),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField(validators=[fleet.validators.validate_model_year])),
                ('active', models.BooleanField(default=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='fleet.office')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[fleet.validators.validate_not_in_future])),
                ('maintenance_type', models.CharField(choices=[('oil_change', 'Oil change'), ('tire_rotation', 'Tire rotation'), ('brake_service', 'Brake service'), ('inspection', 'Inspection'), ('engine_repair', 'Engine repair'), ('transmission', 'Transmission'), ('battery', 'Battery'), ('other', 'Other')], max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True)),
                ('mechanic', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='fleet.mechanic')),
                ('vehicle', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='fleet.vehicle')),
            ],
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('license_plate',), name='uniq_active_license_plate', violation_error_message='Another active vehicle already uses this license plate.'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['vehicle', 'date'], name='record_vehicle_date_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['mechanic', 'date'], name='record_mechanic_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='record_cost_non_negative'),
        ),
    ]
