# Generated by Django 5.2.12 on 2026-10-02 10:39

import django.core.validators
import fleet.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=fleet.models.UpperCaseCharField(max_length=10, validators=[django.core.validators.RegexValidator(message='License plates are letters and digits, optionally separated by single spaces or hyphens.', regex='^[A-Z0-9]+(?:[ -][A-Z0-9]+)*$')]),
        ),
    ]
